Remove `uses-sdk` from plugin.xml
This fixes a `MultipleUsesSdk` lint error that breaks release builds.

```
Error: There should only be a single <uses-sdk> element in the manifest: merge these together [MultipleUsesSdk]
    <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="21" />
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Recent Cordova versions generate a `<uses-sdk>` element with the min SDK set to 14 and the target SDK set to 22.